M48
; DRILL file {KiCad (6.0.11)} date Sat Nov 25 18:10:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-25T18:10:00+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0551
%
G90
G05
T1
X4.7876Y-4.0201
X4.7876Y-4.2476
X6.6533Y-4.0201
X6.6533Y-4.2476
T2
X4.626Y-3.1215
X4.9016Y-3.1215
T0
M30
